# Site Settings
title: Jekflix | A theme for Jekyll
email: erick.major@yahoo.com.br
description: Some text about your blog.
# baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.rossener.com" # the base hostname & protocol for your site
url: "https://erickmajor.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Erick
user_description: Some text about you.
disqus_username: erickmajor

# Social Media
# Remove the item if you don't need it
github_username: erickmajor
# facebook_username: facebook_username
twitter_username: erickmajor
# instagram_username: instagram_username
linkedin_username: erickmajor
medium_username: erickmajor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
