# Site Settings
title: Erick Major | PHP Developer
email: erick.major@yahoo.com.br
description: A blog about development and other things.
# baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erickmajor.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Erick Major
user_description: Some text about you.
disqus_username: erickmajor

# Social Media
# Remove the item if you don't need it
github_username: erickmajor
# facebook_username: facebook_username
twitter_username: erickmajor
# instagram_username: instagram_username
linkedin_username: erickmajor
medium_username: erickmajor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

collections:
  projects:
    project: true
    output: true

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Experience
    url: /experience/
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
